defmodule ElixirCartographer.Synthesis.AgentsMdGenerator do
  @moduledoc """
  Generates the comprehensive AGENTS.md file from analysis data.
  """

  alias ElixirCartographer.Synthesis.MermaidGenerator

  @doc """
  Generate the full AGENTS.md content.
  """
  def generate(analysis) do
    [
      header(analysis),
      project_overview(analysis),
      domain_contexts(analysis),
      workflows_section(analysis),
      api_surface(analysis),
      live_view_section(analysis),
      process_architecture(analysis),
      configuration_matrix(analysis),
      data_model(analysis),
      git_insights(analysis),
      test_coverage(analysis),
      edge_cases(analysis),
      debugging_guide(analysis)
    ]
    |> Enum.join("\n")
  end

  defp header(analysis) do
    """
    # AGENTS.md — #{analysis.config.project_name}

    > Auto-generated by Elixir Cartographer v0.1.0
    > Generated: #{DateTime.utc_now() |> DateTime.to_iso8601()}
    > Source: #{analysis.config.project_path}

    This document provides comprehensive context for AI agents working in this codebase.

    ---

    """
  end

  defp project_overview(analysis) do
    config = analysis.config
    graph = analysis.module_graph
    file_count = length(analysis.source_files)
    module_count = map_size(graph.modules)
    schema_count = length(analysis.schemas)
    context_count = map_size(graph.contexts)

    # Read mix.exs for deps
    deps = extract_deps_from_mix(config.mix_exs_path)

    """
    ## Project Overview

    | Attribute | Value |
    |-----------|-------|
    | **Name** | #{config.project_name} |
    | **Path** | `#{config.project_path}` |
    | **Source Files** | #{file_count} .ex files |
    | **Modules** | #{module_count} |
    | **Ecto Schemas** | #{schema_count} |
    | **Contexts** | #{context_count} |
    | **Git Commits** | #{analysis.git.total_commits} |
    | **Test Files** | #{length(analysis.tests.test_files)} (#{analysis.tests.total_tests} tests) |

    ### Directory Structure

    ```
    #{directory_tree(config.lib_path)}
    ```

    ### Key Dependencies

    #{format_deps(deps)}

    ---

    """
  end

  defp domain_contexts(analysis) do
    contexts = analysis.module_graph.contexts
    schemas = analysis.schemas

    context_sections =
      contexts
      |> Enum.sort_by(fn {name, _} -> name end)
      |> Enum.map(fn {context_name, module_names} ->
        context_schemas = Enum.filter(schemas, fn s ->
          String.contains?(s.module, ".#{context_name}.")
        end)

        context_modules =
          module_names
          |> Enum.take(20)
          |> Enum.map_join("\n", fn name ->
            mod = Map.get(analysis.module_graph.modules, name, %{public_functions: []})
            pub_fns = Map.get(mod, :public_functions, [])
            fn_list = pub_fns |> Enum.take(5) |> Enum.map_join(", ", fn f -> "#{f.name}/#{f.arity}" end)
            suffix = if fn_list != "", do: " — `#{fn_list}`", else: ""
            "- `#{name}`#{suffix}"
          end)

        schema_list =
          if context_schemas != [] do
            context_schemas
            |> Enum.map_join("\n", fn s ->
              fields = s.fields |> Enum.take(8) |> Enum.map_join(", ", fn f -> "#{f.name}: #{f.type}" end)
              "  - **#{s.module}** (#{s.table || "embedded"}) — #{fields}"
            end)
            |> then(&"\n\n  **Schemas:**\n#{&1}")
          else
            ""
          end

        overflow = if length(module_names) > 20, do: "\n- _... and #{length(module_names) - 20} more modules_", else: ""

        """
        ### #{context_name} (#{length(module_names)} modules)

        #{context_modules}#{overflow}#{schema_list}
        """
      end)
      |> Enum.join("\n")

    context_diagram = MermaidGenerator.context_graph(analysis.module_graph)
    diagram_section = if context_diagram != "", do: "\n### Context Dependency Graph\n\n#{context_diagram}\n", else: ""

    """
    ## Domain Contexts

    #{context_sections}#{diagram_section}

    ---

    """
  end

  defp workflows_section(analysis) do
    workflows = analysis.workflows

    if workflows == [] do
      """
      ## Workflows & State Machines

      No explicit workflow/state machine patterns detected.

      ---

      """
    else
      workflow_docs =
        workflows
        |> Enum.map(fn w ->
          status_fields = w.status_fields |> Enum.map_join(", ", fn f -> "`#{f.name}` (#{f.type})" end)
          values = if w.status_values != [], do: w.status_values |> Enum.take(15) |> Enum.map_join(", ", &"`#{&1}`"), else: "_none detected_"
          transitions = if w.transitions != [], do: w.transitions |> Enum.map_join("\n", fn t -> "  - `#{t.function}`" end), else: "  _none detected_"

          """
          ### #{w.module}
          - **Table:** #{w.table || "N/A"}
          - **Status fields:** #{status_fields}
          - **Known values:** #{values}
          - **Transition functions:**
          #{transitions}
          - **Branch points:** #{w.branches} conditional blocks
          """
        end)
        |> Enum.join("\n")

      workflow_diagrams = MermaidGenerator.workflow_diagrams(workflows)
      diagram_section = if workflow_diagrams != "", do: "\n### State Diagrams\n\n#{workflow_diagrams}\n", else: ""

      """
      ## Workflows & State Machines

      #{workflow_docs}#{diagram_section}

      ---

      """
    end
  end

  defp api_surface(analysis) do
    routes = analysis.routes

    route_table =
      if routes.routes != [] do
        routes.routes
        |> Enum.take(50)
        |> Enum.map_join("\n", fn r ->
          "| `#{r.method}` | `#{r.path}` | `#{r.controller}` | `#{r.action}` |"
        end)
        |> then(fn rows ->
          """
          | Method | Path | Controller | Action |
          |--------|------|------------|--------|
          #{rows}
          """
        end)
      else
        "_No traditional routes detected (may use LiveView routing)._"
      end

    # Check for live routes
    live_routes =
      analysis.parsed_files
      |> Enum.filter(fn {path, _} -> String.contains?(path, "router.ex") end)
      |> Enum.flat_map(fn {_path, %{content: content}} ->
        ElixirCartographer.Analyzers.RouteMapper.extract_live_routes(content)
      end)

    live_route_table =
      if live_routes != [] do
        live_routes
        |> Enum.take(50)
        |> Enum.map_join("\n", fn r ->
          "| `#{r.path}` | `#{r.module}` | `#{r.action || "-"}` |"
        end)
        |> then(fn rows ->
          """

          ### LiveView Routes

          | Path | LiveView Module | Action |
          |------|----------------|--------|
          #{rows}
          """
        end)
      else
        ""
      end

    pipeline_docs =
      if routes.pipelines != [] do
        routes.pipelines
        |> Enum.map_join("\n", fn p ->
          plugs = Enum.map_join(p.plugs, ", ", &"`#{&1}`")
          "- **:#{p.name}** — #{plugs}"
        end)
        |> then(&"\n### Pipelines\n\n#{&1}\n")
      else
        ""
      end

    plug_docs =
      if routes.plugs != [] do
        routes.plugs
        |> Enum.map_join("\n", fn p ->
          "- `#{p.module}` — #{p.path}"
        end)
        |> then(&"\n### Custom Plugs\n\n#{&1}\n")
      else
        ""
      end

    overflow_note = if length(routes.routes) > 50, do: "\n_... and #{length(routes.routes) - 50} more routes_\n", else: ""

    """
    ## API Surface

    #{route_table}#{overflow_note}#{live_route_table}#{pipeline_docs}#{plug_docs}

    ---

    """
  end

  defp live_view_section(analysis) do
    lv = Map.get(analysis, :live_view)

    if is_nil(lv) or (lv.live_views == [] and lv.live_components == [] and lv.function_components == []) do
      """
      ## LiveView & Components

      No LiveView patterns detected.

      ---

      """
    else
      lv_docs =
        if lv.live_views != [] do
          lv.live_views
          |> Enum.map(fn v ->
            callbacks = Enum.map_join(v.callbacks, ", ", &"`#{&1}`")
            events = if v.events != [], do: Enum.map_join(v.events, ", ", &"`\"#{&1}\"`"), else: "_none_"
            nav = if v.navigation != [], do: Enum.map_join(v.navigation, ", ", &"`#{&1}`"), else: "_none_"

            """
            - **#{v.module}** — callbacks: #{callbacks}
              - Events: #{events}
              - Navigation: #{nav}
            """
          end)
          |> Enum.join("")
          |> then(&"### LiveView Modules\n\n#{&1}")
        else
          ""
        end

      lc_docs =
        if lv.live_components != [] do
          lv.live_components
          |> Enum.map(fn c ->
            callbacks = Enum.map_join(c.callbacks, ", ", &"`#{&1}`")
            events = if c.events != [], do: Enum.map_join(c.events, ", ", &"`\"#{&1}\"`"), else: "_none_"
            "- **#{c.module}** — callbacks: #{callbacks} | events: #{events}"
          end)
          |> Enum.join("\n")
          |> then(&"\n### LiveComponent Modules\n\n#{&1}\n")
        else
          ""
        end

      fc_docs =
        if lv.function_components != [] do
          lv.function_components
          |> Enum.map(fn fc ->
            attrs = if fc.attrs != [], do: Enum.map_join(fc.attrs, ", ", fn a -> "`#{a.name}` (#{a.type})" end), else: "_none_"
            slots = if fc.slots != [], do: Enum.map_join(fc.slots, ", ", &"`#{&1}`"), else: "_none_"
            heex = if fc.has_heex, do: " ✓ HEEx", else: ""
            "- **#{fc.module}** — attrs: #{attrs} | slots: #{slots}#{heex}"
          end)
          |> Enum.join("\n")
          |> then(&"\n### Function Components\n\n#{&1}\n")
        else
          ""
        end

      # Design patterns summary
      patterns = []
      patterns = if lv.streams_usage != [], do: patterns ++ ["Uses streams for list management"], else: patterns
      patterns = if lv.pubsub_patterns != [], do: patterns ++ ["Uses PubSub for real-time updates"], else: patterns
      patterns = if lv.js_commands != [], do: ["Uses JS commands for client-side interactivity" | patterns], else: patterns
      patterns = if lv.uploads != [], do: patterns ++ ["Uses LiveView uploads"], else: patterns
      patterns = if lv.hooks != [], do: patterns ++ ["Uses JavaScript hooks (#{Enum.map_join(lv.hooks, ", ", &"`#{&1.hook}`")})"], else: patterns

      pattern_docs =
        if patterns != [] do
          patterns
          |> Enum.map_join("\n", &"- #{&1}")
          |> then(&"\n### LiveView Design Patterns\n\n#{&1}\n")
        else
          ""
        end

      """
      ## LiveView & Components

      #{lv_docs}#{lc_docs}#{fc_docs}#{pattern_docs}

      ---

      """
    end
  end

  defp process_architecture(analysis) do
    procs = analysis.processes

    supervisor_docs =
      if procs.supervisors != [] do
        procs.supervisors
        |> Enum.map_join("\n", fn s ->
          children = Enum.take(s.children, 10) |> Enum.map_join(", ", &"`#{&1}`")
          type_label = if Map.get(s, :supervisor_type) == :dynamic_supervisor, do: "DynamicSupervisor", else: "Supervisor"
          "- **#{s.module}** (#{type_label}, strategy: #{s.strategy || "unknown"}) — children: #{children}"
        end)
        |> then(&"### Supervisors\n\n#{&1}\n")
      else
        ""
      end

    genserver_docs =
      if procs.genservers != [] do
        procs.genservers
        |> Enum.map_join("\n", fn g ->
          callbacks = Enum.map_join(g.callbacks, ", ", &"`#{&1}`")
          state = if g.state_shape, do: " — state: #{inspect(g.state_shape)}", else: ""
          "- **#{g.module}** — callbacks: #{callbacks}#{state}"
        end)
        |> then(&"\n### GenServers\n\n#{&1}\n")
      else
        ""
      end

    broadway_docs =
      if procs.broadway != [] do
        procs.broadway
        |> Enum.map_join("\n", fn b ->
          "- **#{b.module}** — producers: #{inspect(b.producers)}"
        end)
        |> then(&"\n### Broadway Pipelines\n\n#{&1}\n")
      else
        ""
      end

    agent_docs =
      if procs.agents != [] do
        procs.agents
        |> Enum.map_join("\n", &"- `#{&1.module}`")
        |> then(&"\n### Agents\n\n#{&1}\n")
      else
        ""
      end

    sup_diagram = MermaidGenerator.supervision_tree(analysis.processes)
    diagram_section = if sup_diagram != "", do: "\n### Supervision Tree\n\n#{sup_diagram}\n", else: ""

    """
    ## Process Architecture

    #{supervisor_docs}#{genserver_docs}#{broadway_docs}#{agent_docs}#{diagram_section}

    ---

    """
  end

  defp configuration_matrix(analysis) do
    cm = analysis.config_matrix

    env_var_table =
      if cm.env_vars != [] do
        cm.env_vars
        |> Enum.take(50)
        |> Enum.map_join("\n", fn v ->
          default = if v.default && v.default != "", do: "`#{v.default}`", else: "-"
          "| `#{v.name}` | #{default} | #{v.source} |"
        end)
        |> then(fn rows ->
          """
          ### Environment Variables

          | Variable | Default | Source |
          |----------|---------|--------|
          #{rows}
          """
        end)
      else
        ""
      end

    overflow = if length(cm.env_vars) > 50, do: "\n_... and #{length(cm.env_vars) - 50} more env vars_\n", else: ""

    app_config_docs =
      if cm.app_configs != [] do
        cm.app_configs
        |> Enum.take(30)
        |> Enum.map_join("\n", fn c ->
          "- `config :#{c.app}, #{c.module}` (#{c.source})"
        end)
        |> then(&"\n### Application Configuration\n\n#{&1}\n")
      else
        ""
      end

    """
    ## Configuration Matrix

    #{env_var_table}#{overflow}#{app_config_docs}

    ---

    """
  end

  defp data_model(analysis) do
    schemas = analysis.schemas

    if schemas == [] do
      """
      ## Data Model

      No Ecto schemas detected.

      ---

      """
    else
      schema_docs =
        schemas
        |> Enum.sort_by(& &1.module)
        |> Enum.map(fn s ->
          fields_table =
            s.fields
            |> Enum.map_join("\n", fn f ->
              "| `#{f.name}` | `#{f.type}` |"
            end)

          assoc_list =
            if s.associations != [] do
              s.associations
              |> Enum.map_join("\n", fn a ->
                "  - #{a.type} :#{a.name} → `#{a.target}`"
              end)
              |> then(&"\n  **Associations:**\n#{&1}")
            else
              ""
            end

          changeset_list =
            if s.changesets != [] do
              s.changesets |> Enum.map_join(", ", &"`#{&1}`")
              |> then(&"\n  **Changesets:** #{&1}")
            else
              ""
            end

          """
          ### #{s.module}
          **Table:** `#{s.table || "embedded"}`  **Type:** #{s.type}

          | Field | Type |
          |-------|------|
          #{fields_table}
          #{assoc_list}#{changeset_list}
          """
        end)
        |> Enum.join("\n")

      erd_diagram = MermaidGenerator.schema_erd(schemas)
      erd_section = if erd_diagram != "", do: "\n### Entity Relationship Diagram\n\n#{erd_diagram}\n", else: ""

      """
      ## Data Model

      #{length(schemas)} Ecto schemas detected.
      #{erd_section}
      #{schema_docs}

      ---

      """
    end
  end

  defp git_insights(analysis) do
    git = analysis.git

    if git.total_commits == 0 do
      """
      ## Git Insights

      Git history not available or skipped.

      ---

      """
    else
      hotspot_docs =
        if git.hotspots != [] do
          git.hotspots
          |> Enum.take(15)
          |> Enum.map_join("\n", fn h ->
            "| `#{h.file}` | #{h.fix_count} |"
          end)
          |> then(fn rows ->
            """
            ### Bug Hotspots (files with most fix commits)

            | File | Fix Commits |
            |------|-------------|
            #{rows}
            """
          end)
        else
          "### Bug Hotspots\n\nNo significant hotspots detected.\n"
        end

      commit_type_docs =
        if git.commit_types != %{} do
          git.commit_types
          |> Enum.sort_by(fn {_, count} -> count end, :desc)
          |> Enum.map_join("\n", fn {type, count} -> "| #{type} | #{count} |" end)
          |> then(fn rows ->
            """
            ### Commit Classification (last 500)

            | Type | Count |
            |------|-------|
            #{rows}
            """
          end)
        else
          ""
        end

      contributor_docs =
        if git.contributors != [] do
          git.contributors
          |> Enum.map_join("\n", fn c -> "| #{c.name} | #{c.commits} |" end)
          |> then(fn rows ->
            """
            ### Top Contributors

            | Name | Commits |
            |------|---------|
            #{rows}
            """
          end)
        else
          ""
        end

      recent_docs =
        if git.recent_activity != [] do
          git.recent_activity
          |> Enum.take(10)
          |> Enum.map_join("\n", fn r -> "| `#{r.file}` | #{r.changes} |" end)
          |> then(fn rows ->
            """
            ### Recent Activity (last 30 days)

            | File | Changes |
            |------|---------|
            #{rows}
            """
          end)
        else
          ""
        end

      """
      ## Git Insights

      **Total commits:** #{git.total_commits}

      #{hotspot_docs}
      #{commit_type_docs}
      #{contributor_docs}
      #{recent_docs}

      ---

      """
    end
  end

  defp test_coverage(analysis) do
    tests = analysis.tests

    if tests.total_tests == 0 do
      """
      ## Test Coverage Map

      No tests found or test mining was skipped.

      ---

      """
    else
      test_summary =
        tests.test_files
        |> Enum.sort_by(& &1.test_count, :desc)
        |> Enum.take(20)
        |> Enum.map_join("\n", fn tf ->
          "| `#{Path.relative_to(tf.path, analysis.config.project_path)}` | #{tf.test_count} |"
        end)

      gap_docs =
        if tests.coverage_gaps != [] do
          tests.coverage_gaps
          |> Enum.take(30)
          |> Enum.map_join("\n", fn g ->
            "- `#{Path.relative_to(g.file, analysis.config.project_path)}`"
          end)
          |> then(&"\n### Coverage Gaps (modules without test files)\n\n#{&1}\n")
        else
          "\n### Coverage Gaps\n\nAll modules appear to have corresponding test files.\n"
        end

      """
      ## Test Coverage Map

      **Total tests:** #{tests.total_tests} across #{length(tests.test_files)} test files

      ### Most-Tested Files

      | Test File | Tests |
      |-----------|-------|
      #{test_summary}
      #{gap_docs}

      ---

      """
    end
  end

  defp edge_cases(analysis) do
    cases = analysis.tests.edge_cases

    if cases == [] do
      """
      ## Known Edge Cases

      No edge cases extracted from tests.

      ---

      """
    else
      case_docs =
        cases
        |> Enum.take(40)
        |> Enum.map_join("\n", fn c ->
          "- **[#{c.type}]** #{c.description} _(#{Path.basename(c.test_file)})_"
        end)

      """
      ## Known Edge Cases

      #{length(cases)} edge/error cases detected from test descriptions:

      #{case_docs}

      ---

      """
    end
  end

  defp debugging_guide(analysis) do
    # Detect logging patterns
    log_patterns = count_log_patterns(analysis.parsed_files)
    telemetry = detect_telemetry(analysis.parsed_files)

    """
    ## Debugging Guide

    ### Logging Patterns

    #{format_log_patterns(log_patterns)}

    ### Telemetry

    #{format_telemetry(telemetry)}

    ### Error Patterns

    #{format_error_patterns(analysis.errors)}

    ---

    _Generated by Elixir Cartographer — https://github.com/your-org/elixir_cartographer_
    """
  end

  # Helper functions

  defp extract_deps_from_mix(mix_path) do
    if File.exists?(mix_path) do
      content = File.read!(mix_path)
      Regex.scan(~r/\{:(\w+),\s*"([^"]*)"/, content)
      |> Enum.map(fn [_, name, version] -> {name, version} end)
      |> Enum.take(30)
    else
      []
    end
  end

  defp format_deps(deps) do
    if deps == [] do
      "_No dependencies detected._"
    else
      deps
      |> Enum.map_join("\n", fn {name, version} -> "- `#{name}` #{version}" end)
    end
  end

  defp directory_tree(lib_path) do
    if File.dir?(lib_path) do
      lib_path
      |> File.ls!()
      |> Enum.sort()
      |> Enum.map(fn entry ->
        full_path = Path.join(lib_path, entry)
        if File.dir?(full_path) do
          subdirs = File.ls!(full_path) |> Enum.filter(&File.dir?(Path.join(full_path, &1))) |> Enum.sort()
          if subdirs != [] do
            sub_tree = Enum.map_join(subdirs, "\n", &"  ├── #{&1}/")
            "#{entry}/\n#{sub_tree}"
          else
            "#{entry}/"
          end
        else
          entry
        end
      end)
      |> Enum.join("\n")
    else
      "_lib/ directory not found_"
    end
  end

  defp count_log_patterns(parsed_files) do
    parsed_files
    |> Enum.reduce(%{debug: 0, info: 0, warn: 0, warning: 0, error: 0}, fn {_path, %{content: content}}, acc ->
      %{
        debug: acc.debug + count_occurrences(content, "Logger.debug"),
        info: acc.info + count_occurrences(content, "Logger.info"),
        warn: acc.warn + count_occurrences(content, "Logger.warn"),
        warning: acc.warning + count_occurrences(content, "Logger.warning"),
        error: acc.error + count_occurrences(content, "Logger.error")
      }
    end)
  end

  defp count_occurrences(string, pattern) do
    string |> String.split(pattern) |> length() |> Kernel.-(1) |> max(0)
  end

  defp format_log_patterns(patterns) do
    """
    | Level | Count |
    |-------|-------|
    | Logger.debug | #{patterns.debug} |
    | Logger.info | #{patterns.info} |
    | Logger.warning | #{patterns.warning + patterns.warn} |
    | Logger.error | #{patterns.error} |
    """
  end

  defp detect_telemetry(parsed_files) do
    parsed_files
    |> Enum.flat_map(fn {path, %{content: content}} ->
      telemetry_pattern = ~r/:telemetry\.execute\(\[([^\]]+)\]/
      Regex.scan(telemetry_pattern, content)
      |> Enum.map(fn [_, event] -> %{event: event, source: Path.basename(path)} end)
    end)
  end

  defp format_telemetry(events) do
    if events == [] do
      "_No explicit telemetry events detected. May use library-provided telemetry._"
    else
      events
      |> Enum.take(20)
      |> Enum.map_join("\n", fn e -> "- `[#{e.event}]` (#{e.source})" end)
    end
  end

  defp format_error_patterns(errors) do
    if errors == [] do
      "_No explicit error patterns detected._"
    else
      error_summary =
        errors
        |> Enum.group_by(& &1.type)
        |> Enum.map(fn {type, items} -> "- **#{type}**: #{length(items)} occurrences" end)
        |> Enum.join("\n")

      rescue_types =
        errors
        |> Enum.filter(&(&1.type == :rescue))
        |> Enum.flat_map(fn e -> Map.get(e, :exceptions, []) end)
        |> Enum.frequencies()
        |> Enum.sort_by(fn {_, c} -> c end, :desc)
        |> Enum.take(10)
        |> Enum.map_join("\n", fn {type, count} -> "  - `#{type}` (#{count}x)" end)

      """
      #{error_summary}

      **Most rescued exceptions:**
      #{rescue_types}
      """
    end
  end
end
