defmodule ElixirCartographer.Synthesis.ContextDocsGenerator do
  @moduledoc """
  Generates per-context documentation files for the docs/ folder.
  """

  @doc """
  Generate a list of {filename, content} tuples for per-context docs.
  """
  def generate(analysis) do
    contexts = analysis.module_graph.contexts
    compact = Map.get(analysis.config, :compact, false)

    context_docs =
      contexts
      |> Enum.map(fn {context_name, module_names} ->
        filename = "#{String.downcase(context_name)}.md"
        content =
          if compact do
            generate_compact_context_doc(context_name, module_names, analysis)
          else
            generate_context_doc(context_name, module_names, analysis)
          end
        {filename, content}
      end)

    # Also generate an index
    index = generate_index(contexts, analysis)
    [{"_index.md", index} | context_docs]
  end

  defp generate_context_doc(context_name, module_names, analysis) do
    modules = analysis.module_graph.modules
    schemas = analysis.schemas

    context_schemas =
      schemas
      |> Enum.filter(fn s -> String.contains?(s.module, ".#{context_name}.") end)

    context_modules =
      module_names
      |> Enum.map(fn name -> {name, Map.get(modules, name)} end)
      |> Enum.reject(fn {_, mod} -> is_nil(mod) end)

    # Find related tests
    related_tests =
      analysis.tests.test_files
      |> Enum.filter(fn tf ->
        String.contains?(tf.path, String.downcase(context_name))
      end)

    # Find related git activity
    related_hotspots =
      analysis.git.hotspots
      |> Enum.filter(fn h ->
        String.contains?(h.file, String.downcase(context_name))
      end)

    live_view_docs = format_live_view_section(context_name, analysis)

    """
    # #{context_name} Context

    ## Overview

    This context contains #{length(module_names)} modules#{if context_schemas != [], do: " and #{length(context_schemas)} Ecto schemas", else: ""}.

    ## Modules

    #{format_module_list(context_modules)}

    #{format_schemas_section(context_schemas)}
    #{live_view_docs}

    ## Tests

    #{format_tests_section(related_tests, analysis)}

    #{format_hotspots_section(related_hotspots)}

    ---
    _Generated by Elixir Cartographer_
    """
  end

  defp generate_compact_context_doc(context_name, module_names, analysis) do
    modules = analysis.module_graph.modules
    schemas = analysis.schemas

    context_schemas =
      schemas
      |> Enum.filter(fn s -> String.contains?(s.module, ".#{context_name}.") end)

    module_lines =
      module_names
      |> Enum.map(fn name ->
        mod = Map.get(modules, name, %{public_functions: []})
        pub_fns = Map.get(mod, :public_functions, [])
        fn_list = pub_fns |> Enum.take(8) |> Enum.map_join(", ", fn f -> "#{f.name}/#{f.arity}" end)
        if fn_list != "", do: "- #{name} — #{fn_list}", else: "- #{name}"
      end)
      |> Enum.join("\n")

    schema_lines =
      if context_schemas != [] do
        context_schemas
        |> Enum.map(fn s ->
          fields = s.fields |> Enum.take(8) |> Enum.map_join(", ", fn f -> "#{f.name}:#{f.type}" end)
          assocs = if s.associations != [] do
            s.associations |> Enum.map_join(", ", fn a -> "#{a.type} → #{a.target}" end) |> then(&" | #{&1}")
          else
            ""
          end
          "- #{s.module} (#{s.table || "embedded"}) — #{fields}#{assocs}"
        end)
        |> Enum.join("\n")
        |> then(&"\n## Schemas\n#{&1}\n")
      else
        ""
      end

    """
    # #{context_name} Context
    #{length(module_names)} modules#{if context_schemas != [], do: ", #{length(context_schemas)} schemas", else: ""}

    ## Modules
    #{module_lines}
    #{schema_lines}
    ---
    _Generated by Elixir Cartographer_
    """
  end

  defp format_module_list(modules) do
    modules
    |> Enum.map(fn {name, mod} ->
      pub_fns = Map.get(mod, :public_functions, [])
      uses = Map.get(mod, :uses, [])
      behaviours = Map.get(mod, :behaviours, [])

      parts = []
      parts = if uses != [], do: parts ++ ["uses: #{Enum.join(uses, ", ")}"], else: parts
      parts = if behaviours != [], do: parts ++ ["behaviours: #{Enum.join(behaviours, ", ")}"], else: parts
      parts = parts ++ ["#{length(pub_fns)} public functions"]

      fn_summary =
        pub_fns
        |> Enum.take(10)
        |> Enum.map_join("\n", fn f -> "  - `#{f.name}/#{f.arity}`" end)

      """
      ### `#{name}`

      #{Enum.join(parts, " | ")}

      #{if fn_summary != "", do: "**Public API:**\n#{fn_summary}", else: ""}
      """
    end)
    |> Enum.join("\n")
  end

  defp format_schemas_section([]), do: ""
  defp format_schemas_section(schemas) do
    schema_docs =
      schemas
      |> Enum.map(fn s ->
        fields = s.fields |> Enum.map_join("\n", fn f -> "  - `#{f.name}`: #{f.type}" end)

        assocs =
          if s.associations != [] do
            s.associations
            |> Enum.map_join("\n", fn a -> "  - #{a.type} :#{a.name} → #{a.target}" end)
            |> then(&"\n**Associations:**\n#{&1}")
          else
            ""
          end

        """
        ### Schema: `#{s.module}`

        **Table:** `#{s.table || "embedded"}`

        **Fields:**
        #{fields}
        #{assocs}
        """
      end)
      |> Enum.join("\n")

    """
    ## Schemas

    #{schema_docs}
    """
  end

  defp format_tests_section([], _analysis), do: "_No tests found for this context._"
  defp format_tests_section(test_files, analysis) do
    total = Enum.reduce(test_files, 0, fn tf, acc -> acc + tf.test_count end)

    file_list =
      test_files
      |> Enum.map_join("\n", fn tf ->
        "- `#{Path.relative_to(tf.path, analysis.config.project_path)}` (#{tf.test_count} tests)"
      end)

    """
    **#{total} tests** across #{length(test_files)} files:

    #{file_list}
    """
  end

  defp format_hotspots_section([]), do: ""
  defp format_hotspots_section(hotspots) do
    """
    ## Git Hotspots

    These files have the most bug-fix commits:

    #{Enum.map_join(hotspots, "\n", fn h -> "- `#{h.file}` (#{h.fix_count} fixes)" end)}
    """
  end

  defp format_live_view_section(context_name, analysis) do
    lv = Map.get(analysis, :live_view)

    if is_nil(lv) do
      ""
    else
      ctx_lower = String.downcase(context_name)

      live_views =
        Enum.filter(lv.live_views, fn v ->
          String.downcase(v.module) |> String.contains?(ctx_lower)
        end)

      live_components =
        Enum.filter(lv.live_components, fn c ->
          String.downcase(c.module) |> String.contains?(ctx_lower)
        end)

      function_components =
        Enum.filter(lv.function_components, fn fc ->
          String.downcase(fc.module) |> String.contains?(ctx_lower)
        end)

      if live_views == [] and live_components == [] and function_components == [] do
        ""
      else
        parts = []

        parts =
          if live_views != [] do
            lv_list =
              Enum.map_join(live_views, "\n", fn v ->
                events = if v.events != [], do: " — events: #{Enum.join(v.events, ", ")}", else: ""
                "- `#{v.module}`#{events}"
              end)

            parts ++ ["**LiveViews:**\n#{lv_list}"]
          else
            parts
          end

        parts =
          if live_components != [] do
            lc_list = Enum.map_join(live_components, "\n", fn c -> "- `#{c.module}`" end)
            parts ++ ["**LiveComponents:**\n#{lc_list}"]
          else
            parts
          end

        parts =
          if function_components != [] do
            fc_list = Enum.map_join(function_components, "\n", fn fc -> "- `#{fc.module}`" end)
            parts ++ ["**Function Components:**\n#{fc_list}"]
          else
            parts
          end

        """
        ## LiveView & Components

        #{Enum.join(parts, "\n\n")}
        """
      end
    end
  end

  defp generate_index(contexts, analysis) do
    context_list =
      contexts
      |> Enum.sort_by(fn {name, _} -> name end)
      |> Enum.map_join("\n", fn {name, modules} ->
        schemas_in = Enum.count(analysis.schemas, fn s -> String.contains?(s.module, ".#{name}.") end)
        schema_note = if schemas_in > 0, do: " (#{schemas_in} schemas)", else: ""
        "- [#{name}](#{String.downcase(name)}.md) — #{length(modules)} modules#{schema_note}"
      end)

    """
    # #{analysis.config.project_name} — Context Documentation Index

    > Generated by Elixir Cartographer

    ## Contexts

    #{context_list}

    ## Quick Stats

    - **Total modules:** #{map_size(analysis.module_graph.modules)}
    - **Total schemas:** #{length(analysis.schemas)}
    - **Total tests:** #{analysis.tests.total_tests}
    - **Git commits:** #{analysis.git.total_commits}
    """
  end
end
